### ISSUE TITLE
uploadId should be url-safe [JIRA: RCS-350]

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#1063] opened 2015-01-30 06:19 UTC
In v4 authentication, query parameters are used at signing like this (s3cmd example):

```
DEBUG: Canonical Request:
PUT
/40MB
partNumber=1&uploadId=8YSbOd4lQVqbgprjS-VKAw==
content-length:15728640
```

Characters like `=` should not be there or it should be url encoded by clients.
c.f. #1062

**Comment by shino** [comment] 2015-01-30 06:42
It's nice to avoid client-side corner case bugs because such query param normalization is specific to S3 AND v4 auth. But I want to note that it is not a bug of riak cs, and s3cmd should be fixed.

**Comment by bashoshaun** [comment] 2016-02-03 09:42
The uploadId is not considered a query parameter in Amazon's [signing documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html).  It is considered a subresource, and therefore falls under different rules of URL encoding/decoding as query parameters.

Subresources form part of the CanonicalizedResource and when signing, should be left either URL encoded or decoded, as specified in the original URI.

I believe Riak CS is treating uploadId as a query parameter, and following the rules for signing by first URL-decoding them.  Under these rules, it looks like Riak CS is exhibiting a bug.

**Closed as completed** 2016-03-04 00:39 UTC
Labels: Enhancement, JIRA: Needs Review

**Comment by Basho-JIRA** [comment] 2016-06-01 17:15
Approved by Dave McCrory to create a 2.0 patch for Nokia.  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment] 2016-06-01 21:16
Previously fixed and included in Riak CS 2.1.2

Nokia patch is issue RCS-366 

**_[posted via JIRA by Ted Burghart]**_

**Comment by Basho-JIRA** [comment] 2016-06-03 18:49
Changing this back to "To Do" status because the code, and the test for it, in the merged fix is incorrect.

The code happens to work when encoding/decoding UUIDs because their encoded length hits the midpoint in calculating how many '=' characters belong at the tail the properly encoded Base64, but variable length data will trigger a crash if the Base64 encoding would have an odd number of trailing '=' characters.

Additionally, the regular expression used to test the new code will never match, even if the code produced the wrong result.  Since the test only uses UUIDs, which by chance produce the right result because of their length, the test never sees data that exposes the decoding flaw. 

**_[posted via JIRA by Ted Burghart]**_

**Comment by Basho-JIRA** [comment] 2016-06-03 19:17
2.1.2 will need to be rebuilt, when we are the point of working on it again, correct?  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment] 2016-06-03 19:27
Once this is fixed correctly, 2.1.2 will beed to be rebuilt and tested.  It won't need any RN changes, as they already say it's fixed. 

**_[posted via JIRA by Ted Burghart]**_

**Comment by Basho-JIRA** [comment] 2016-06-04 14:00
https://github.com/basho/riak_cs/pull/1316 

**_[posted via JIRA by Ted Burghart]**_

**Comment by tburghart** [comment] 2016-06-04 14:19
https://github.com/basho/riak_cs/pull/1316
