### ISSUE TITLE
Change to API in 1.5.4 should include upgrade/downgrade script [JIRA: RCS-198]

### ISSUE THREAD

**Issue by jhmullen** [basho/riak_cs#1142] opened 2015-05-01 14:37 UTC
Issue #910 was fixed in Riak CS 1.5.4, which addressed improperly encoded object names (with the potential for keyspace collision).  The details on this are explained here:

https://github.com/basho/riak_cs/blob/develop/releasenotes/riak-cs.1.md#notes-on-upgrading

However, there is no way at the Riak level to compensate for what is essentially a breaking API change.  If users have objects stored that are affected by the "+" vs " " issue, and they upgrade to 1.5.4, those objects will essentially be orphaned/invisible.  There should be an upgrade/downgrade script (akin to the 2i sext encoding `reformat-indexes` utility) that assists users in migrating their objects to and from this change in behavior.  

See zd://10707 for more details.

**Comment by kuenishi** [comment] 2015-05-12 08:51
The problem is, any tool cannot find original key name back. It's not obvious and only the application knows (or even don't). The problem is not `+` and space, but also a doubly URL-encoded keys. Say key A and B were stored both in B. B is stored in Riak as a key. The name has been lost. We can't know whether B _used to be_ A or B when it was put. We can write a tool that force all Bs to be As, but I'm not sure that kind of tool needed.

**Comment by shino** [comment] 2016-01-19 05:36
As @kuenishi explained, automatic resolution/upgrade/downgrade can not be done. It requires external information, for example all URLs for PUT Object from load balancer in front of Riak CS (it might not be sufficient).

I will close this, but please feel free to re-open if anyone has better idea for migration.

**Closed as completed by shino** 2016-01-19 05:36 UTC
Labels: JIRA: To Do
