### ISSUE TITLE
WM error when S3 file upload is aborted [JIRA: RCS-163]

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#243] opened 2012-07-16 14:06 UTC
Using basho_bench to rate-limit the S3 file uploads.  When basho_bench's time is done, all in-progress uploads report this error (e.g. dozens or hundreds of times, depending on the # of basho_bench worker processes):

```
=ERROR REPORT==== 16-Jul-2012::09:03:10 ===
webmachine error: path="/test/65"
{error,
  {error,
    {badmatch,{error,closed}},
    [{webmachine_request,recv_unchunked_body,4,
         [{file,"src/webmachine_request.erl"},{line,432}]},
     {riak_moss_wm_key,accept_streambody,4,
         [{file,"src/riak_moss_wm_key.erl"},{line,419}]},
     {webmachine_resource,resource_call,3,
         [{file,"src/webmachine_resource.erl"},{line,166}]},
     {webmachine_resource,do,3,
         [{file,"src/webmachine_resource.erl"},{line,125}]},
     {webmachine_decision_core,resource_call,1,
         [{file,"src/webmachine_decision_core.erl"},{line,48}]},
     {webmachine_decision_core,accept_helper,0,
         [{file,"src/webmachine_decision_core.erl"},{line,583}]},
     {webmachine_decision_core,decision,1,
         [{file,"src/webmachine_decision_core.erl"},{line,489}]},
     {webmachine_decision_core,handle_request,2,
         [{file,"src/webmachine_decision_core.erl"},{line,33}]}]}}
```

**Comment by shino** [comment] 2015-03-30 02:57
duplicate of #479

**Closed as completed by shino** 2015-03-30 02:57 UTC
Labels: Bug, JIRA: Closed, JIRA: Done
