### ISSUE TITLE
Bucket access by non-owner causes an error.

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#185] opened 2012-04-18 19:03 UTC
riak_moss_wm_bucket:shift_to_owner calls riak_moss_utils:get_user with a binary representation of the key_id when it expects a string and this causes a badarg error.

Riak CS console output follows:

(riak-cs@127.0.0.1)1> 12:57:01.334 [error] webmachine error: path="/testbucket/"
{error,badarg,[{erlang,list_to_binary,[<<"Q5U52KT6JYEF2EUPL8DP">>],[]},{riak_moss_utils,get_user,2,[{file,"src/riak_moss_utils.erl"},{line,279}]},{riak_moss_wm_bucket,shift_to_owner,4,[{file,"src/riak_moss_wm_bucket.erl"},{line,120}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,166}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,125}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,198}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,33}]}]}

**Comment by slfritchie** [comment] 2012-04-23 18:18
Kelly, could you be more specific about how to trigger this error?  Or else perhaps it no longer exists, perhaps due to the Dialyzer cleanup?  See https://gist.github.com/fe77b8daf8f2040d5de0 for a script that tries to provoke it.

**Comment by slfritchie** [comment] 2012-04-23 20:50
Reproducing script for the 1.0 branch: https://gist.github.com/b98acecace0aa032cb8e

**Comment by slfritchie** [comment] 2012-04-23 20:53
https://github.com/basho/riak_moss/pull/192

**Comment by slfritchie** [comment] 2012-04-28 05:22
merged

**Closed as completed by slfritchie** 2012-04-28 05:22 UTC
