### ISSUE TITLE
Boto test sometimes fails. It seems like a race. 

### ISSUE THREAD

**Issue by andrewjstone** [basho/riak_cs#559] opened 2013-05-08 16:59 UTC
Andrews-MacBook-Pro:python ajs$ ./env/bin/nosetests -m 'test_normal_object_metadata' boto_test.py
# F
## FAIL: test_normal_object_metadata (boto_test.ObjectMetadataTest)

Traceback (most recent call last):
  File "/Users/ajs/riak_cs/client_tests/python/boto_test.py", line 548, in test_normal_object_metadata
    self.assert_updated_metadata(bucket, key_name)
  File "/Users/ajs/riak_cs/client_tests/python/boto_test.py", line 591, in assert_updated_metadata
    'attachment; filename="newname.txt"')
AssertionError: 'attachment; filename="metaname.txt"' != 'attachment; filename="newname.txt"'
-------------------- >> begin captured logging << --------------------
boto: DEBUG: Using access key provided by client.
boto: DEBUG: Using secret key provided by client.
boto: DEBUG: path=/2d5fa572-1e51-400b-99c8-5e878ee43201/
boto: DEBUG: auth_path=/2d5fa572-1e51-400b-99c8-5e878ee43201/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /2d5fa572-1e51-400b-99c8-5e878ee43201/
boto: DEBUG: Data:
boto: DEBUG: Headers: {}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT

Wed, 08 May 2013 16:53:39 GMT
/2d5fa572-1e51-400b-99c8-5e878ee43201/
boto: DEBUG: Signature:
AWS OMOZBZJRFLXHD0A7CXRQ:9N0XOzn1pFnPFBvpjmqnYtX9/Qg=
boto: DEBUG: path=/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: auth_path=/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Data:
boto: DEBUG: Headers: {'x-amz-meta-UID': '0', 'Content-Length': '27', 'Content-Disposition': 'attachment; filename="metaname.txt"', 'Content-Encoding': 'identity', 'x-amz-meta-mtime': '1364742057', 'Expires': 'Tue, 19 Jan 2038 03:14:07 GMT', 'User-Agent': 'Boto/2.9.0 (darwin)', 'Expect': '100-Continue', 'x-amz-meta-with-hypen': '1', 'Content-MD5': 'Qz/JyQzNgB0Lk+5IH23AKA==', 'Content-Type': 'application/octet-stream'}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
Qz/JyQzNgB0Lk+5IH23AKA==
application/octet-stream
Wed, 08 May 2013 16:53:39 GMT
x-amz-meta-mtime:1364742057
x-amz-meta-uid:0
x-amz-meta-with-hypen:1
/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Signature:
AWS OMOZBZJRFLXHD0A7CXRQ:5F+2yIGPXISljhi5vO0JzcZHGIc=
boto: DEBUG: path=/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: auth_path=/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Method: GET
boto: DEBUG: Path: /2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Data:
boto: DEBUG: Headers: {}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
GET

Wed, 08 May 2013 16:53:39 GMT
/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Signature:
AWS OMOZBZJRFLXHD0A7CXRQ:aM/2XEzSncleBOL+XQkRExeafLI=
boto: DEBUG: path=/2d5fa572-1e51-400b-99c8-5e878ee43201/
boto: DEBUG: auth_path=/2d5fa572-1e51-400b-99c8-5e878ee43201/
boto: DEBUG: path=/2d5fa572-1e51-400b-99c8-5e878ee43201/?&max-keys=0
boto: DEBUG: auth_path=/2d5fa572-1e51-400b-99c8-5e878ee43201/?&max-keys=0
boto: DEBUG: Method: GET
boto: DEBUG: Path: /2d5fa572-1e51-400b-99c8-5e878ee43201/?&max-keys=0
boto: DEBUG: Data:
boto: DEBUG: Headers: {}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
GET

Wed, 08 May 2013 16:53:39 GMT
/2d5fa572-1e51-400b-99c8-5e878ee43201/
boto: DEBUG: Signature:
AWS OMOZBZJRFLXHD0A7CXRQ:YLL2FrUThwNhsLYqRauNS1omCJQ=
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>2d5fa572-1e51-400b-99c8-5e878ee43201</Name><Prefix></Prefix><Marker></Marker><MaxKeys>0</MaxKeys><Delimiter></Delimiter><IsTruncated>false</IsTruncated></ListBucketResult>
boto: DEBUG: path=/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: auth_path=/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Data:
boto: DEBUG: Headers: {'x-amz-meta-uid': '0', 'x-amz-meta-new-entry': 'NEW', 'Content-Disposition': 'attachment; filename="newname.txt"', 'x-amz-storage-class': 'STANDARD', 'x-amz-meta-mtime': '2222222222', 'Expires': 'Tue, 19 Jan 2038 03:14:07 GMT', 'x-amz-copy-source': '2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451', 'x-amz-metadata-directive': 'REPLACE'}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT

Wed, 08 May 2013 16:53:39 GMT
x-amz-copy-source:2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
x-amz-meta-mtime:2222222222
x-amz-meta-new-entry:NEW
x-amz-meta-uid:0
x-amz-metadata-directive:REPLACE
x-amz-storage-class:STANDARD
/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Signature:
AWS OMOZBZJRFLXHD0A7CXRQ:4k8F4XNDzeRvdOtbVRQB0j+vVdA=
boto: DEBUG: path=/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: auth_path=/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Method: GET
boto: DEBUG: Path: /2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Data:
boto: DEBUG: Headers: {}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
GET

Wed, 08 May 2013 16:53:40 GMT
/2d5fa572-1e51-400b-99c8-5e878ee43201/39327407-cbb4-4a2f-a19f-ecee722ce451
boto: DEBUG: Signature:
AWS OMOZBZJRFLXHD0A7CXRQ:oe6vCw87PyMlPOYToPW2+cnPfiY=
--------------------- >> end captured logging << ---------------------

---

Ran 1 test in 1.133s

FAILED (failures=1)

**Comment by kellymclaughlin** [comment] 2013-05-10 17:57
Closing. Determined root cause and PR for resolution is [here](https://github.com/basho/riak_cs/pull/563).

**Closed as completed by kellymclaughlin** 2013-05-10 17:57 UTC
Labels: Kanban-Cabal-CS
