### ISSUE TITLE
Querying storage usage returns empty result when bucket is nearly empty [JIRA: RCS-169]

### ISSUE THREAD

**Issue by ponta1024** [basho/riak_cs#766] opened 2014-01-06 00:54 UTC
Run storage calculation batch every hour.

```
{storage_schedule,["0100","0200","0300","0400","0500","0600","0700","0800","0900","1000","1100","1200","1300","1400","1500","1600","1700","1800","1900","2000","2100","2200","2300","0000"]},
```

Query storage usage for the period corresponding to above storage schedule (e.g. 05:00:00) which I believe should return the storage samples taken at 05:00:00. It actually returns empty result.

```
# s3curl.pl --id ponta -- -s -x localhost:8080 http://riak-cs.s3.amazonaws.com/usage/JQAFJOYQ6HGGGDGHMYGG/b/20131228T050000Z/20131228T060000Z | python -m json.tool
{
    "Access": "not_requested",
    "Storage": {
        "Errors": [],
        "Samples": []
    }
}
```

If I shift the query range a bit it will successfully return the stats. 

```
# s3curl.pl --id ponta -- -s -x localhost:8080 http://riak-cs.s3.amazonaws.com/usage/JQAFJOYQ6HGGGDGHMYGG/b/20131228T045959Z/20131228T060000Z | python -m json.tool
{
    "Access": "not_requested",
    "Storage": {
        "Errors": [],
        "Samples": [
            {
                "EndTime": "20131228T050000Z",
                "StartTime": "20131228T050000Z",
                "bucket777": {
                    "Bytes": 2097152,
                    "Objects": 1
                },
<snip>
```

Seems that it only happens when the storage batch completes less than a second and StartTime and EndTime is the same.

```
                "EndTime": "20131228T050000Z",
                "StartTime": "20131228T050000Z",
```

**Comment by shino** [comment] 2015-03-30 04:59
duplicate of #978

**Closed as completed by shino** 2015-03-30 04:59 UTC
Labels: Kanban-Backlog, JIRA: Closed, JIRA: Done
