### ISSUE TITLE
GC daemon cannot start collection when too much to-be-gc'd keys in Riak

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#590] opened 2013-06-12 15:58 UTC
When the query range (in timestamp) is too wide or too much timestamps in a fixed time range, get_index may be timeout and GC can't started.

``` erlang
gc_index_query(RiakPid, EndTime) ->
    QueryResult = riakc_pb_socket:get_index(RiakPid,
                                            ?GC_BUCKET,
                                            ?KEY_INDEX,
                                            riak_cs_gc:epoch_start(),
                                            EndTime),
    {QueryResult, EndTime}.
```

https://github.com/basho/riak_cs/blob/develop/src/riak_cs_gc_d.erl#L387

**Comment by reiddraper** [comment] 2013-06-12 18:02
This is mostly a duplicate of #253. Closing in favor of #579, which will be used to track the fix.

**Closed as completed by reiddraper** 2013-06-12 18:02 UTC
Labels: Kanban-Backlog, Kanban-Cabal-CS

**Comment by kuenishi** [comment] 2013-06-12 22:48
Great! I thought I might have reviewed set of existing issues not to duplicate but failed. Thanks!
