### ISSUE TITLE
Could not listing users based on status. [JIRA: RCS-334]

### ISSUE THREAD

**Issue by d5nguyenvan** [basho/riak_cs#659] opened 2013-08-29 18:27 UTC
I write a program that listing all users based on status but risk-cs return all users in current system.

Step to reproduce.
1. Create some users (example 4 users) (all users are enable)
2. Listing diabled user using /riak-cs/users?status=disabled, all users will return.

The debug log:

2013-08-30 01:07:03,426 DEBUG - Sending request: GET /riak-cs/users?status=disabled HTTP/1.1
2013-08-30 01:07:03,426 DEBUG - >> "GET /riak-cs/users?status=disabled HTTP/1.1[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> "Action: ListUsers[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> "Authorization: AWS KIVENI1VRWZWB6OXCBCK:rzye0l5O1nrsbj3l5gjz3Zl+3Tw=[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> "Content-Type: application/xml[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> "Date: Thu, 29 Aug 2013 18:07:03 GMT[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> "User-Agent: http-auth-client-java/1.0.0 Mac_OS_X/10.8.4 Java_HotSpot(TM)_64-Bit_Server_VM/20.51-b01-456[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> "Version: 2013-08-29[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> "Connection: Keep-Alive[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> "[\r][\n]"
2013-08-30 01:07:03,426 DEBUG - >> GET /riak-cs/users?status=disabled HTTP/1.1
2013-08-30 01:07:03,426 DEBUG - >> Host: xxx.xxx.xxx
2013-08-30 01:07:03,426 DEBUG - >> Action: ListUsers
2013-08-30 01:07:03,427 DEBUG - >> Authorization: AWS KIVENI1VRWZWB6OXCBCK:rzye0l5O1nrsbj3l5gjz3Zl+3Tw=
2013-08-30 01:07:03,427 DEBUG - >> Content-Type: application/xml
2013-08-30 01:07:03,427 DEBUG - >> Date: Thu, 29 Aug 2013 18:07:03 GMT
2013-08-30 01:07:03,427 DEBUG - >> User-Agent: http-auth-client-java/1.0.0 Mac_OS_X/10.8.4 Java_HotSpot(TM)_64-Bit_Server_VM/20.51-b01-456
2013-08-30 01:07:03,427 DEBUG - >> Version: 2013-08-29
2013-08-30 01:07:03,427 DEBUG - >> Connection: Keep-Alive
2013-08-30 01:07:03,480 DEBUG - << "HTTP/1.1 200 OK[\r][\n]"
2013-08-30 01:07:03,480 DEBUG - << "Date: Thu, 29 Aug 2013 18:08:26 GMT[\r][\n]"
2013-08-30 01:07:03,480 DEBUG - << "Server: Riak CS[\r][\n]"
2013-08-30 01:07:03,481 DEBUG - << "Vary: Accept[\r][\n]"
2013-08-30 01:07:03,481 DEBUG - << "Content-Type: multipart/mixed; boundary=H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX[\r][\n]"
2013-08-30 01:07:03,481 DEBUG - << "Via: 1.1 xxx.xxx.xxx[\r][\n]"
2013-08-30 01:07:03,481 DEBUG - << "Connection: close[\r][\n]"
2013-08-30 01:07:03,481 DEBUG - << "Transfer-Encoding: chunked[\r][\n]"
2013-08-30 01:07:03,481 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,481 DEBUG - Receiving response: HTTP/1.1 200 OK
2013-08-30 01:07:03,481 DEBUG - << HTTP/1.1 200 OK
2013-08-30 01:07:03,481 DEBUG - << Date: Thu, 29 Aug 2013 18:08:26 GMT
2013-08-30 01:07:03,481 DEBUG - << Server: Riak CS
2013-08-30 01:07:03,481 DEBUG - << Vary: Accept
2013-08-30 01:07:03,481 DEBUG - << Content-Type: multipart/mixed; boundary=H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX
2013-08-30 01:07:03,481 DEBUG - << Via: 1.1 xxx.xxx.xxx
2013-08-30 01:07:03,481 DEBUG - << Connection: close
2013-08-30 01:07:03,481 DEBUG - << Transfer-Encoding: chunked
2013-08-30 01:07:03,483 DEBUG - Multipart boundary: H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX
2013-08-30 01:07:03,495 DEBUG - << "1a9[\r][\n]"
2013-08-30 01:07:03,495 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,496 DEBUG - << "--H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX[\r][\n]"
2013-08-30 01:07:03,496 DEBUG - << "Content-Type: application/xml[\r][\n]"
2013-08-30 01:07:03,496 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,496 DEBUG - << "<?xml version="1.0" encoding="UTF-8"?><Users><User><Email>tttduyen@inetcloud.vn</Email><DisplayName>tttduyen</DisplayName><Name>Duyen Tang</Name><KeyId>removed</KeyId><KeySecret>removed</KeySecret><Id>f3feece5ae2fd4ad3ddfc54d161959a61fc28f18be4dc1213e7609c1659fc0af</Id><Status> <b>enabled</b> </Status></User></Users>"
2013-08-30 01:07:03,496 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,533 DEBUG - << "2d9[\r][\n]"
2013-08-30 01:07:03,533 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,533 DEBUG - << "--H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX[\r][\n]"
2013-08-30 01:07:03,533 DEBUG - << "Content-Type: application/xml[\r][\n]"
2013-08-30 01:07:03,533 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,533 DEBUG - << "<?xml version="1.0" encoding="UTF-8"?><Users><User><Email>tttduyen@yahoo.com</Email><DisplayName>tttduyen</DisplayName><Name>Tang TT Duyen</Name><KeyId>AHL8MQG8C4EOFM-CHLA-</KeyId><KeySecret>remove</KeySecret><Id>removed</Id><Status> <b>enabled</b> </Status></User><User><Email>admin@inetcloud.vn</Email><DisplayName>admin</DisplayName><Name>iNet Administrator</Name><KeyId>removed</KeyId><KeySecret>removed</KeySecret><Id>b63456d22fcd3943ee8004639406bebc79d45e0fa4118ac46d33cf531dbb6bf7</Id><Status> <b>enabled</b> </Status></User></Users>"
2013-08-30 01:07:03,534 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,534 DEBUG - << "1b0[\r][\n]"
2013-08-30 01:07:03,534 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,534 DEBUG - << "--H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX[\r][\n]"
2013-08-30 01:07:03,534 DEBUG - << "Content-Type: application/xml[\r][\n]"
2013-08-30 01:07:03,534 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,534 DEBUG - << "<?xml version="1.0" encoding="UTF-8"?><Users><User><Email>tttduyen@inetcloud.com.vn</Email><DisplayName>tttduyen</DisplayName><Name>Duyen Tang TT</Name><KeyId>Z8CYK_3LBTUG2BGVA_KD</KeyId><KeySecret>removed</KeySecret><Id>removed</Id><Status> <b>enabled</b> </Status></User></Users>"
2013-08-30 01:07:03,535 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,535 DEBUG - << "1af[\r][\n]"
2013-08-30 01:07:03,535 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,535 DEBUG - << "--H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX[\r][\n]"
2013-08-30 01:07:03,535 DEBUG - << "Content-Type: application/xml[\r][\n]"
2013-08-30 01:07:03,535 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,535 DEBUG - << "<?xml version="1.0" encoding="UTF-8"?><Users><User><Email>tttduyen@gmail.com</Email><DisplayName>tttduyen</DisplayName><Name>Tang Thi Thuy Duyen</Name><KeyId>removed</KeyId><KeySecret>removed</KeySecret><Id>a1ebdcaa3bd21bcb6018f9f9a1e776b99af3a81f6af128b584329e92d5ef2b00</Id><Status><b>enabled</b></Status></User></Users>"
2013-08-30 01:07:03,536 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,536 DEBUG - << "74[\r][\n]"
2013-08-30 01:07:03,536 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,536 DEBUG - << "--H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX[\r][\n]"
2013-08-30 01:07:03,536 DEBUG - << "Content-Type: application/xml[\r][\n]"
2013-08-30 01:07:03,536 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,536 DEBUG - << "<?xml version="1.0" encoding="UTF-8"?><Users/>"
2013-08-30 01:07:03,537 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,537 DEBUG - << "25[\r][\n]"
2013-08-30 01:07:03,537 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,537 DEBUG - << "--H78NAQC1ZY38DS9ZR1IDLK5D77EG8XX--"
2013-08-30 01:07:03,537 DEBUG - << "[\r][\n]"
2013-08-30 01:07:03,537 DEBUG - << "0[\r][\n]"
2013-08-30 01:07:03,537 DEBUG - << "[\r][\n]"

**Comment by shino** [comment] 2016-01-20 00:41
This is not a bug, but a spec. As described in [1] , API to list users does not accept status or any other query parameters.

It may be useful for filtering functionality at API level in a system with many (>millions?) users. Otherwise, filtering after listing all users will work.

I will close this issue but please feel free to file new issue with use cases where such functionality is useful. Thanks for reporting.

[1] http://docs.basho.com/riakcs/latest/cookbooks/Account-Management/#Retrieving-a-List-of-All-Users

**Closed as completed by shino** 2016-01-20 00:41 UTC
Labels: Kanban-Backlog, JIRA: To Do
